### ISSUE TITLE
[Enhancement] Command confirmation

### ISSUE THREAD

**Issue by slimeMMVI** [Revxrsal/Lamp#103]
Works like this, could be a new annotation (@Confirmation), that when added to a command method, requires the player to execute the command again to actually execute the command. Would be nice to also add configuration in the annotation, some examples are:
expireAfter: How long of a time frame the command executor has to execute the command again
console: If the re-execution of the command should work if the command was executed from console

**Comment by creatorfromhell** [comment]
I feel like this is more implementation specific, and is opening up for requests for functionality that will add a lot of unnecessary fluff. I think this is something that in all honesty for modern Minecraft would be better off left up to implementations because some, myself included, would prefer a text click event and then the functionality becomes dead and just takes up space in the library.

**Comment by Revxrsal** [comment]
As mentioned above, such features are specific to certain use cases and do not fit in the mainstream library. Furthermore, you can use the library's mechanisms to implement it (CommandConditions, for example).
