### ISSUE TITLE
Allow invalid usernames (GeyserMC/Floodgate)

### ISSUE THREAD

**Issue by SkytAsul** [Revxrsal/Lamp#39]
An user of my plugin using Lamp on a GeyserMC+Floodgate server is having this issue while trying to execute a command with a player selector:
![](https://cdn.discordapp.com/attachments/1055260795598032966/1055260896840122429/image.png)
He sent me his Floodgate config:
```yml
# Floodgate prepends a prefix to bedrock usernames to avoid conflicts
# However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
# It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
username-prefix: '*'
```
It seems like Lamp recognizes the star as an incorrect username character and completely blocks player selector from there.
Is it possible to fix this, or at least have an option somewhere to allow "unsafe" usernames?
Some plugins do have such options: LuckPerms have a `allow-invalid-usernames` boolean config option, and ChestChop have a `VALID_PLAYERNAME_REGEXP` regex option.

**Comment by Revxrsal** [comment]
Players are resolved with the simple `Bukkit.getPlayerExact(...)`. I frankly don't know how GeyserMC works or what does it change in the standard Bukkit, but you can override the `Player` resolver using something like this:
```java
                                     v
commandHandler.registerValueResolver(0, Player.class, context -> {
// change how players are resolved
}```
Or, you could simply create your own Player wrapper type, or instead require a String instead of a Player in your command.

**Comment by SkytAsul** [comment]
Unfortunately I am using an EntitySelector, not a simple Player.

**Comment by Revxrsal** [comment]
You can follow the same procedure for EntitySelector then, albeit it's probably more tedious. Lamp uses `Bukkit.selectEntities(selector string)` for that. You could override it to take into consideration Bedrock players. 
I'm really not aware of how GeyserMC works or what APIs it provides, so I'd rather keep it as it is instead of pulling in a half-baked solution, especially since the fix is possible.

**Comment by SkytAsul** [comment]
Well, for now I found a workaround by telling the user to set `_` as the Geyser prefix instead of `*` and it worked. Would have been nice to simply being able to change the validation expression.

**Comment by Revxrsal** [comment]
Lamp doesn't have any validation regarding player names. It simply checks the result of `Bukkit#selectEntities`, and if it's empty, or fails due to an invalid expression, it throws an error.

**Comment by SkytAsul** [comment]
Then maybe add an optional fallback option to try `Bukkit#getPlayerExact(expression)` in the case where `selectEntities` failed? It would probably fix the issue.

**Comment by Grabsky** [comment]
I don't think it's in the scope of Lamp to fix incompatibilities with other plugins and especially with protocol hacks. You can, however, fix that yourself by registering a `ValueResolverFactory` for `Player` type with `0` priority which would effectively override the default one.

**Comment by SkytAsul** [comment]
> I don't think it's in the scope of Lamp to fix incompatibilities with other plugins and especially - with protocol hacks.

I understand that.

> You can, however, fix that yourself by registering a `ValueResolverFactory` for `Player` type with `0` priority which would effectively override the default one.

That's not what I want, if you had read my comments you would have understood that I want an EntitySelector, not a basic Player.

In the end, I might register a custom EntitySelector value resolver which will basically a copy of the Lamp integrated one with the `Bukkit#getPlayerExact` fallback... not ideal but still.

**Comment by Grabsky** [comment]
> That's not what I want, if you had read my comments you would have understood that I want an EntitySelector, not a basic Player.
Apologize, turns out I missed a bunch of comments including those suggesting you to do the exact same thing.

> In the end, I might register a custom EntitySelector value resolver which will basically a copy of the Lamp integrated one with the Bukkit#getPlayerExact fallback... not ideal but still.
This is a valid fix for the issue you're experiencing and shouldn't be too hard to implement. Depending on the Minecraft version you're developing plugin for, as well as the targetted Java version, you may also benefit from stripping legacy support from the default `EntitySelector` implementation Lamp provides. Other than that, it is - as you already mentioned - as simple as copying the code and adding the `Bukkit#getPlayerExact` fallback (which hopefully fixes the original issue).

**Comment by Revxrsal** [comment]
You could, perhaps, use `Either<Player, EntitySelector>`. This will combine the 2 resolvers and get you the result you may be looking for.
