### ISSUE TITLE
[Question] Command alias from config

### ISSUE THREAD

**Issue by Ciph3r-Zer0** [Revxrsal/Lamp#92]
Hello,
Is there a way to set a commands aliases from a list that is retrieved from a config file?

**Comment by Ciph3r-Zer0** [comment]
To explain more of my question:
The only way I see for setting a commands aliases is thro annotation and that does not allow any further customizebility customizability other that hard coding the aliases
I'm asking for is, for e.g get a list of string from config and set it as aliases for a command

**Comment by Wector11211** [comment]
You want to use [orphan commands](https://github.com/Revxrsal/Lamp/wiki/Orphan-commands).

For example, let `commandAliases` an array retrieved from the config, then instead of
```java
commandHandler.register(new FooCommand());
```
you write
```java
commandHandler.register(Orphans.path(commandAliases).handler(new FooCommand()));
```
Note that you need to make your`FooCommand` implement `OrphanCommand`, it's just an empty interface used for declaring purposes
```java
public class FooCommand implements OrphanCommand {
    // ...
}
```

**Comment by Ciph3r-Zer0** [comment]
Thanks for helping me,

I tried what you told and it does not seem to workout 

I created a simple orphan command like this:
`@Command("heal")
    fun heal(sender: Player) {
        sender.health = sender.maxHealth
    }`

and registered like you told me to:

`commandHandler = BukkitCommandHandler.create(this)
        commandHandler.registerBrigadier()

        commandHandler.register(Orphans.path("feed").handler(HealCommand()));`

however executing /heal command works as intended but executing /feed returns Unknown command error

**Comment by Ciph3r-Zer0** [comment]
Thanks for helping me,

I tried what you told and it does not seem to workout 

I created a simple orphan command like this:
```
@Command("heal")
    fun heal(sender: Player) {
        sender.health = sender.maxHealth
    }
```

and registered like you told me to:

```
commandHandler = BukkitCommandHandler.create(this)
 commandHandler.registerBrigadier()
commandHandler.register(Orphans.path("feed").handler(HealCommand()));
```

however executing /heal command works as intended but executing /feed returns Unknown command error

**Comment by Wector11211** [comment]
That's because orphans are bound to a class, so you need to use
```kt
class HealCommand: OrphanCommand {
    @DefaultFor("~")
    fun heal(sender: Player) {
       sender.health = sender.maxHealth
    }
}
```
```kt
commandHandler.register(Orphans.path("heal", "feed").handler(HealCommand()));
```
---
In general it's convenient yet a good practice to have a class to be annotated as `@Command` and build the inner structure within it
```java
@Command("foo")
public class FooCommand {
    @DefaultFor({"~", "~ help"})
    public void foo() {
    // run /foo or /foo help
    }

    @Subcommand("bar")
    public void bar() {
        // run /foo bar
    }
    
    @Subcommand("baz")
    public static class Baz {
        @Subcommand("one")
        public void one() {
            // run /foo baz one
        }
        @Subcommand("two")
        public void one() {
            // run /foo baz two
        }
    }
}
```
---
Note `@DefaultFor` which got an additional `~` syntax since `3.1.7` to support root reference. Wiki is not updating that often, unfortunately, but you can join [discord](https://discord.gg/pEGGF785zp) where all most recent changes are discussed.

**Comment by Ciph3r-Zer0** [comment]
Thanks you so much for helping me out
it is now working as I want it to
